
# .github/workflows/build-darwin.yml
name: Build macOS Releases
on:
  workflow_call:
    inputs:
      arch:
        type: string
        required: true
    secrets:
      BUILD_CERTIFICATE_BASE64:
        required: true
      APPLE_PASSWORD:
        required: true
      APPLE_ID:
        required: true
      APPLE_TEAM_ID:
        required: true
      IDENTIFY_DARWIN_CODE:
        required: true
jobs:
  build-darwin:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get-package-version
        id: package-version
        uses: beaconbrigade/package-json-version@v0.3.2
      - name: Import certificate
        run: chmod +x ./build/import_apple_cert.sh && ./build/import_apple_cert.sh
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: setup appdmg
        run: |
          python3 -m pip install setuptools
          npm install -g appdmg@0.6.6          
      - name: Install Dependencies
        run: npm ci
      - name: Build script
        run: make mac-${{ inputs.arch }}
        env:
          PREBUILDS_ONLY: "1"
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          IDENTIFY_DARWIN_CODE: ${{ secrets.IDENTIFY_DARWIN_CODE }}
      - name: List packages
        uses: mathiasvr/command-output@v2.0.0
        id: packagelist
        with:
          run: node ./build/list_packages.mjs
      - name: Publish Release
        run: gh release upload v${{ steps.package-version.outputs.version}} ${{ steps.packagelist.outputs.stdout }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
